Update automatic

diff --git a/automatic b/automatic
--- a/automatic
+++ b/automatic
@@ -61,12 +61,14 @@ install_revix() {
     echo "✅ Revix/Reviactyl theme installed!"
 }
 
-# Function: install aura theme
-install_aura() {
-    echo "Installing Aura theme...."
-    apt install curl -y
-    bash <(curl -s https://raw.githubusercontent.com/TS-25/SRJ-THEME/refs/heads/main/aura-theme)
-    echo "Successfull!"
+# Function: Install MC Plugin Addon
+install_subdomain() {
+    echo "🛠️ Installing MC Plugin Addon..."
+    apt install wget -y
+    cd /var/www/pterodactyl || { echo "❌ Pterodactyl not found!"; exit 1; }
+    wget -O subdomains.blueprint https://github.com/TS-25/SRJ-THEME/releases/latest/download/subdomains.blueprint
+    blueprint -install subdomains
+    echo "✅ Subdomain Addon installed!"
 }
 
 # Menu
@@ -80,7 +82,7 @@ while true; do
     echo "3) Euphoria Theme(blueprint)"
     echo "4) Plugin Installer Addon(blueprint)(premium)"
     echo "5) Revix/Reviactyl Theme(without blueprint)"
-    echo "6) Aura theme(blueprint)"
+    echo "6) Subdomain(blueprint)"
     echo "7) Exit"
     echo "==============================="
     read -rp "Choose an option [1-7]: " choice
@@ -91,7 +93,7 @@ while true; do
         3) install_euphoria ;;
         4) install_mcplugins ;;
         5) install_revix ;;
-        6) install_aura ;;
+        6) install_subdomain ;;
         7) echo "👋 Exiting..."; exit 0 ;;
         *) echo "❌ Invalid choice! Try again." ;;
     esac
